### ISSUE TITLE
Complete Storyboards

### ISSUE THREAD

**Issue by MikeS2058** [MikeS2058/RatonClassifieds.com#1]
Complete storyboards based on personas.

**Comment by jim2044** [comment]
Las Animas County Out Side iof the Mountain
![Diamond T Fisher Peak Background 1980's.jpg](https://zube.io/files/raton-classifieds/b633deffe880efc4c5eeae06732e4d2d.jpeg)

**Comment by jim2044** [comment]
Seaway to Colorado across the boarder New Mexico. This was an adjustment for a tractor that my parents' did not have.

**Comment by jim2044** [comment]
Welcome to the South West where your either good or your history.
I know people that are both.
![Pump_up_hill_to_top_ditch_Coolie_Place_River_Trinidad +150.jpg](https://zube.io/files/raton-classifieds/01488976fdeab805e786d568df01bee1.jpeg)

**Comment by MikeS2058** [comment]
Was closed by mistake during initial setup.
